---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  data_bags_path: test/support/data_bags
  encrypted_data_bag_secret_key_path: test/support/encrypted_data_bag_secret

platforms:
  - name: ubuntu-14.04
  - name: centos-6.6

# Setup default suite in .kitchen.local.yml, see .kitchen.local.yml.EXAMPLE for details!
