driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.6
  - name: ubuntu-14.04

# For testing joining the domain, see .kitchen.local.yml.EXAMPLE
suites:
  - name: default
    run_list:
      - recipe[sssd::default]
      - recipe[test-helper::serverspec]
    attributes:
      sssd:
        directory_name: 'ldap.example.com'
        join_domain: false
