---
driver:
  name: vagrant
  customize:
    memory: 2048

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.2

platforms:
  - name: centos-6.6
  - name: ubuntu-14.04

# For testing joining the domain, see .kitchen.local.yml.EXAMPLE
suites:
  - name: default
    run_list:
      - recipe[sssd::default]
      - recipe[test-helper::default]
    attributes:
      sssd:
        directory_name: 'ldap.example.com'
        join_domain: false
